version: "3.6"
services:

  api:
    build: .
    environment:
      IP_SERVER: "185.51.247.27"
      PORT_SERVER: 10010

    volumes:
      - ./:/main
    ports:
      - "10020:10020"
    network_mode: "host"
